### ISSUE TITLE
Nothing

### ISSUE THREAD

**Issue by ImagicalGamer** [UniversMakers/GladiatorMine#7]

**Comment by matthew4444** [comment]
wtf

**Comment by matthew4444** [comment]
deleting this post now

**Comment by erkam2002** [comment]
?

**Comment by matthew4444** [comment]
i closed the post i ment to say

**Comment by ImagicalGamer** [comment]
I want those removed.

**Comment by ImagicalGamer** [comment]
If you didn't notice almost all plugs on your forums are stolen, me and the other creators want them removed.

**Comment by matthew4444** [comment]
u want them removed,ill give credits

**Comment by ImagicalGamer** [comment]
My plugins have very strict terms of use and licenses that state you have no rights to any part of the plugin, or rights to modify and/or redistribute them. That goes for TheKnightTeam as well (SuperSmashMobs). As for the other plugs I'm sure you will hear from their creators soon.

**Comment by matthew4444** [comment]
kk im at school ill do it at home

**Comment by Taki21** [comment]
Tthx for inviting me but @matthew4444 Please DO Not take my plugin : DiamondNether
and sell it! At least ask me and Ill see and give me credit (FULL)

**Comment by matthew4444** [comment]
kk np im drry

**Comment by matthew4444** [comment]
they were ?

**Comment by matthew4444** [comment]
some of them dont speak english !
